*&---------------------------------------------------------------------*
*& Include          Z_DEC_BANCO_ALFA02_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK CRUD1 WITH FRAME TITLE TITLEN1 NO INTERVALS.

  PARAMETERS: P_CREATE RADIOBUTTON GROUP BBDD,  " Create
              P_READ   RADIOBUTTON GROUP BBDD,  " Read
              P_UPDATE RADIOBUTTON GROUP BBDD,  " Update
              P_DELETE RADIOBUTTON GROUP BBDD,  " Delete
              P_MODIFY RADIOBUTTON GROUP BBDD.  " Modify

SELECTION-SCREEN END OF BLOCK CRUD1.

SELECTION-SCREEN BEGIN OF BLOCK ADD1 WITH FRAME TITLE TITLE1 NO INTERVALS.

PARAMETERS: P_SOC   TYPE BUKRS OBLIGATORY,
            P_EJER   TYPE N LENGTH 4 OBLIGATORY,
             P_PERIO  TYPE N LENGTH 2 OBLIGATORY.

SELECTION-SCREEN END OF BLOCK ADD1.

* group Business partner

SELECTION-SCREEN BEGIN OF BLOCK ADD2 WITH FRAME TITLE TITLE2 NO INTERVALS.

PARAMETERS: P_ACRE RADIOBUTTON GROUP BUPA,
            P_DEUD RADIOBUTTON GROUP BUPA .

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS P_TEST AS CHECKBOX.
            SELECTION-SCREEN COMMENT (12) C_TEST.

PARAMETERS P_NOTIF AS CHECKBOX DEFAULT 'X'.
            SELECTION-SCREEN COMMENT (18) C_NOTIF.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK ADD2.

* block 3
SELECTION-SCREEN BEGIN OF BLOCK ADD3 WITH FRAME TITLE TITLE3 NO INTERVALS.

SELECT-OPTIONS: S_CUENTA  FOR BSIK-LIFNR,
                S_CLASE   FOR BSIK-UMSKS,
                S_FECHA   FOR BSIK-AUGDT,
                S_DOC     FOR BSIK-BELNR.

SELECTION-SCREEN END OF BLOCK ADD3.
