CLASS zcl_airlines01_alfa02 DEFINITION
  PUBLIC FINAL CREATE PUBLIC .
    PUBLIC SECTION.
    interfaces if_amdp_marker_hdb.

    CLASS-METHODS GET_AIRLINES IMPORTING VALUE(LV_AIRLINE_NAME) TYPE s_carrname
                                         VALUE(IV_THRESHOLD) TYPE decimal3_01
                               EXPORTING VALUE(ET_AIRLINES) TYPE TY_SCARR.
ENDCLASS.



CLASS zcl_airlines01_alfa02 IMPLEMENTATION.

  METHOD get_airlines BY DATABASE PROCEDURE
    FOR HDB LANGUAGE SQLSCRIPT OPTIONS READ-ONLY USING SCARR.

    ET_AIRLINES = SELECT * FROM SCARR
                    WHERE CONTAINS( CARRNAME, :LV_AIRLINE_NAME, FUZZY( :IV_THRESHOLD) );

  ENDMETHOD.

ENDCLASS.
