CLASS zcl_tf_amdp_alfa02 DEFINITION
  PUBLIC FINAL CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_amdp_marker_hdb.


  CLASS-METHODS GET_PLANES FOR TABLE FUNCTION ZCDS_TF_AMDP_ALFA02.

ENDCLASS.



CLASS zcl_tf_amdp_alfa02 IMPLEMENTATION.

  METHOD get_planes BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY USING SAPLANE.

    LT_RESULT = SELECT SAPL.mandt, SAPL.Planetype, SAPL.seatsmax, SAPL.producer
        FROM SAPLANE AS SAPL
            WHERE SAPL.mandt = :CLNT ;

    RETURN SELECT * FROM :LT_RESULT;

  ENDMETHOD.

ENDCLASS.
