*&---------------------------------------------------------------------*
*& Include ZDXYZ10_PBO
*&---------------------------------------------------------------------*

*&SPWIZARD: OUTPUT MODULE FOR TS 'ZTAB'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE ZTAB_ACTIVE_TAB_SET OUTPUT.
  ZTAB-ACTIVETAB = G_ZTAB-PRESSED_TAB.
  CASE G_ZTAB-PRESSED_TAB.
    WHEN C_ZTAB-TAB1.
      G_ZTAB-SUBSCREEN = '0101'.
    WHEN C_ZTAB-TAB2.
      G_ZTAB-SUBSCREEN = '0102'.
    WHEN C_ZTAB-TAB3.
      G_ZTAB-SUBSCREEN = '0103'.
    WHEN C_ZTAB-TAB4.
      G_ZTAB-SUBSCREEN = '0104'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBLE_CNT'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TBLE_CNT_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE LT_EMP LINES TBLE_CNT-lines.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBLE_CNT'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GET LINES OF TABLECONTROL
MODULE TBLE_CNT_GET_LINES OUTPUT.
  G_TBLE_CNT_LINES = SY-LOOPC.
ENDMODULE.
