*&---------------------------------------------------------------------*
*& Include ZDXYZ8_PBO
*&---------------------------------------------------------------------*

*&SPWIZARD: OUTPUT MODULE FOR TS 'TBC3'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE TBC3_ACTIVE_TAB_SET OUTPUT.
  TBC3-ACTIVETAB = G_TBC3-PRESSED_TAB.
  CASE G_TBC3-PRESSED_TAB.
    WHEN C_TBC3-TAB1.
      G_TBC3-SUBSCREEN = '0101'.
    WHEN C_TBC3-TAB2.
      G_TBC3-SUBSCREEN = '0102'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBC4'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TBC4_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE IT_KNA1 LINES TBC4-lines.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBC5'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TBC5_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE IT_VBAK LINES TBC5-lines.
ENDMODULE.
