*&---------------------------------------------------------------------*
*& Include ZDXYZ20_PBO
*&---------------------------------------------------------------------*

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBLE_CNT1'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TBLE_CNT1_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE LT_EMP LINES TBLE_CNT1-lines.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TBLE_CNT1'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GET LINES OF TABLECONTROL
MODULE TBLE_CNT1_GET_LINES OUTPUT.
  G_TBLE_CNT1_LINES = SY-LOOPC.
ENDMODULE.
