*&---------------------------------------------------------------------*
*& Include ZDXYZ8_DATA
*&---------------------------------------------------------------------*

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'TBC3'
CONSTANTS: BEGIN OF C_TBC3,
             TAB1 LIKE SY-UCOMM VALUE 'TBC3_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TBC3_FC2',
           END OF C_TBC3.
*&SPWIZARD: DATA FOR TABSTRIP 'TBC3'
CONTROLS:  TBC3 TYPE TABSTRIP.
DATA:      BEGIN OF G_TBC3,
             SUBSCREEN   LIKE SY-DYNNR,
             PROG        LIKE SY-REPID VALUE 'ZDXYZ8',
             PRESSED_TAB LIKE SY-UCOMM VALUE C_TBC3-TAB1,
           END OF G_TBC3.
DATA:      OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TBC4' ITSELF
CONTROLS: TBC4 TYPE TABLEVIEW USING SCREEN 0101.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TBC5' ITSELF
CONTROLS: TBC5 TYPE TABLEVIEW USING SCREEN 0102.
