TYPE-POOL ZFA02 .

CONSTANTS: ZFA02_TARIFA_TECNICO TYPE I VALUE 80,
           ZFA02_TARIFA_PROGRAMADOR TYPE I VALUE 100.

TYPES: BEGIN OF ZFA02_TIPO_CNTR,
         TIPO_CNTR TYPE ZTIPO_CNTR_ALFA02,
         HORAS_SEN TYPE I,
         DIAS_VAC TYPE I,
       END OF ZFA02_TIPO_CNTR.
