*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVA_MARD1_ALFA02................................*
FORM GET_DATA_ZVA_MARD1_ALFA02.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM MARD WHERE
(VIM_WHERETAB) .
    CLEAR ZVA_MARD1_ALFA02 .
ZVA_MARD1_ALFA02-MANDT =
MARD-MANDT .
ZVA_MARD1_ALFA02-MATNR =
MARD-MATNR .
ZVA_MARD1_ALFA02-WERKS =
MARD-WERKS .
ZVA_MARD1_ALFA02-LGORT =
MARD-LGORT .
ZVA_MARD1_ALFA02-LFGJA =
MARD-LFGJA .
ZVA_MARD1_ALFA02-LFMON =
MARD-LFMON .
ZVA_MARD1_ALFA02-UMLME =
MARD-UMLME .
ZVA_MARD1_ALFA02-INSME =
MARD-INSME .
<VIM_TOTAL_STRUC> = ZVA_MARD1_ALFA02.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVA_MARD1_ALFA02 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVA_MARD1_ALFA02.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVA_MARD1_ALFA02-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM MARD WHERE
  MATNR = ZVA_MARD1_ALFA02-MATNR AND
  WERKS = ZVA_MARD1_ALFA02-WERKS AND
  LGORT = ZVA_MARD1_ALFA02-LGORT .
    IF SY-SUBRC = 0.
    DELETE MARD .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM MARD WHERE
  MATNR = ZVA_MARD1_ALFA02-MATNR AND
  WERKS = ZVA_MARD1_ALFA02-WERKS AND
  LGORT = ZVA_MARD1_ALFA02-LGORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR MARD.
    ENDIF.
MARD-MANDT =
ZVA_MARD1_ALFA02-MANDT .
MARD-MATNR =
ZVA_MARD1_ALFA02-MATNR .
MARD-WERKS =
ZVA_MARD1_ALFA02-WERKS .
MARD-LGORT =
ZVA_MARD1_ALFA02-LGORT .
MARD-LFGJA =
ZVA_MARD1_ALFA02-LFGJA .
MARD-LFMON =
ZVA_MARD1_ALFA02-LFMON .
MARD-UMLME =
ZVA_MARD1_ALFA02-UMLME .
MARD-INSME =
ZVA_MARD1_ALFA02-INSME .
    IF SY-SUBRC = 0.
    UPDATE MARD ##WARN_OK.
    ELSE.
    INSERT MARD .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVA_MARD1_ALFA02-UPD_FLAG,
STATUS_ZVA_MARD1_ALFA02-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVA_MARD1_ALFA02.
  SELECT SINGLE * FROM MARD WHERE
MATNR = ZVA_MARD1_ALFA02-MATNR AND
WERKS = ZVA_MARD1_ALFA02-WERKS AND
LGORT = ZVA_MARD1_ALFA02-LGORT .
ZVA_MARD1_ALFA02-MANDT =
MARD-MANDT .
ZVA_MARD1_ALFA02-MATNR =
MARD-MATNR .
ZVA_MARD1_ALFA02-WERKS =
MARD-WERKS .
ZVA_MARD1_ALFA02-LGORT =
MARD-LGORT .
ZVA_MARD1_ALFA02-LFGJA =
MARD-LFGJA .
ZVA_MARD1_ALFA02-LFMON =
MARD-LFMON .
ZVA_MARD1_ALFA02-UMLME =
MARD-UMLME .
ZVA_MARD1_ALFA02-INSME =
MARD-INSME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVA_MARD1_ALFA02 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVA_MARD1_ALFA02-MATNR TO
MARD-MATNR .
MOVE ZVA_MARD1_ALFA02-WERKS TO
MARD-WERKS .
MOVE ZVA_MARD1_ALFA02-LGORT TO
MARD-LGORT .
MOVE ZVA_MARD1_ALFA02-MANDT TO
MARD-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'MARD'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN MARD TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'MARD'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
