*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVA_EKPO_ALFA02.................................*
FORM GET_DATA_ZVA_EKPO_ALFA02.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM EKPO WHERE
(VIM_WHERETAB) .
    CLEAR ZVA_EKPO_ALFA02 .
ZVA_EKPO_ALFA02-MANDT =
EKPO-MANDT .
ZVA_EKPO_ALFA02-EBELN =
EKPO-EBELN .
ZVA_EKPO_ALFA02-EBELP =
EKPO-EBELP .
ZVA_EKPO_ALFA02-LOEKZ =
EKPO-LOEKZ .
ZVA_EKPO_ALFA02-STATU =
EKPO-STATU .
ZVA_EKPO_ALFA02-AEDAT =
EKPO-AEDAT .
ZVA_EKPO_ALFA02-TXZ01 =
EKPO-TXZ01 .
ZVA_EKPO_ALFA02-MATNR =
EKPO-MATNR .
<VIM_TOTAL_STRUC> = ZVA_EKPO_ALFA02.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVA_EKPO_ALFA02 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVA_EKPO_ALFA02.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVA_EKPO_ALFA02-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM EKPO WHERE
  EBELN = ZVA_EKPO_ALFA02-EBELN AND
  EBELP = ZVA_EKPO_ALFA02-EBELP .
    IF SY-SUBRC = 0.
    DELETE EKPO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM EKPO WHERE
  EBELN = ZVA_EKPO_ALFA02-EBELN AND
  EBELP = ZVA_EKPO_ALFA02-EBELP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR EKPO.
    ENDIF.
EKPO-MANDT =
ZVA_EKPO_ALFA02-MANDT .
EKPO-EBELN =
ZVA_EKPO_ALFA02-EBELN .
EKPO-EBELP =
ZVA_EKPO_ALFA02-EBELP .
EKPO-LOEKZ =
ZVA_EKPO_ALFA02-LOEKZ .
EKPO-STATU =
ZVA_EKPO_ALFA02-STATU .
EKPO-AEDAT =
ZVA_EKPO_ALFA02-AEDAT .
EKPO-TXZ01 =
ZVA_EKPO_ALFA02-TXZ01 .
EKPO-MATNR =
ZVA_EKPO_ALFA02-MATNR .
    IF SY-SUBRC = 0.
    UPDATE EKPO ##WARN_OK.
    ELSE.
    INSERT EKPO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVA_EKPO_ALFA02-UPD_FLAG,
STATUS_ZVA_EKPO_ALFA02-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVA_EKPO_ALFA02.
  SELECT SINGLE * FROM EKPO WHERE
EBELN = ZVA_EKPO_ALFA02-EBELN AND
EBELP = ZVA_EKPO_ALFA02-EBELP .
ZVA_EKPO_ALFA02-MANDT =
EKPO-MANDT .
ZVA_EKPO_ALFA02-EBELN =
EKPO-EBELN .
ZVA_EKPO_ALFA02-EBELP =
EKPO-EBELP .
ZVA_EKPO_ALFA02-LOEKZ =
EKPO-LOEKZ .
ZVA_EKPO_ALFA02-STATU =
EKPO-STATU .
ZVA_EKPO_ALFA02-AEDAT =
EKPO-AEDAT .
ZVA_EKPO_ALFA02-TXZ01 =
EKPO-TXZ01 .
ZVA_EKPO_ALFA02-MATNR =
EKPO-MATNR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVA_EKPO_ALFA02 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVA_EKPO_ALFA02-EBELN TO
EKPO-EBELN .
MOVE ZVA_EKPO_ALFA02-EBELP TO
EKPO-EBELP .
MOVE ZVA_EKPO_ALFA02-MANDT TO
EKPO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'EKPO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN EKPO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'EKPO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
