*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVA_ALFA02......................................*
FORM GET_DATA_ZVA_ALFA02.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEMPLE_ALFA02 WHERE
(VIM_WHERETAB) .
    CLEAR ZVA_ALFA02 .
ZVA_ALFA02-MANDT =
ZEMPLE_ALFA02-MANDT .
ZVA_ALFA02-NUM_DIR =
ZEMPLE_ALFA02-NUM_DIR .
ZVA_ALFA02-NOMBRE =
ZEMPLE_ALFA02-NOMBRE .
ZVA_ALFA02-APELLIDO1 =
ZEMPLE_ALFA02-APELLIDO1 .
ZVA_ALFA02-APELLIDO2 =
ZEMPLE_ALFA02-APELLIDO2 .
ZVA_ALFA02-CAT_PROF =
ZEMPLE_ALFA02-CAT_PROF .
ZVA_ALFA02-STATUS =
ZEMPLE_ALFA02-STATUS .
ZVA_ALFA02-PAIS =
ZEMPLE_ALFA02-PAIS .
<VIM_TOTAL_STRUC> = ZVA_ALFA02.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVA_ALFA02 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVA_ALFA02.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVA_ALFA02-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLE_ALFA02 WHERE
  NUM_DIR = ZVA_ALFA02-NUM_DIR .
    IF SY-SUBRC = 0.
    DELETE ZEMPLE_ALFA02 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLE_ALFA02 WHERE
  NUM_DIR = ZVA_ALFA02-NUM_DIR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEMPLE_ALFA02.
    ENDIF.
ZEMPLE_ALFA02-MANDT =
ZVA_ALFA02-MANDT .
ZEMPLE_ALFA02-NUM_DIR =
ZVA_ALFA02-NUM_DIR .
ZEMPLE_ALFA02-NOMBRE =
ZVA_ALFA02-NOMBRE .
ZEMPLE_ALFA02-APELLIDO1 =
ZVA_ALFA02-APELLIDO1 .
ZEMPLE_ALFA02-APELLIDO2 =
ZVA_ALFA02-APELLIDO2 .
ZEMPLE_ALFA02-CAT_PROF =
ZVA_ALFA02-CAT_PROF .
ZEMPLE_ALFA02-STATUS =
ZVA_ALFA02-STATUS .
ZEMPLE_ALFA02-PAIS =
ZVA_ALFA02-PAIS .
    IF SY-SUBRC = 0.
    UPDATE ZEMPLE_ALFA02 ##WARN_OK.
    ELSE.
    INSERT ZEMPLE_ALFA02 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVA_ALFA02-UPD_FLAG,
STATUS_ZVA_ALFA02-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVA_ALFA02.
  SELECT SINGLE * FROM ZEMPLE_ALFA02 WHERE
NUM_DIR = ZVA_ALFA02-NUM_DIR .
ZVA_ALFA02-MANDT =
ZEMPLE_ALFA02-MANDT .
ZVA_ALFA02-NUM_DIR =
ZEMPLE_ALFA02-NUM_DIR .
ZVA_ALFA02-NOMBRE =
ZEMPLE_ALFA02-NOMBRE .
ZVA_ALFA02-APELLIDO1 =
ZEMPLE_ALFA02-APELLIDO1 .
ZVA_ALFA02-APELLIDO2 =
ZEMPLE_ALFA02-APELLIDO2 .
ZVA_ALFA02-CAT_PROF =
ZEMPLE_ALFA02-CAT_PROF .
ZVA_ALFA02-STATUS =
ZEMPLE_ALFA02-STATUS .
ZVA_ALFA02-PAIS =
ZEMPLE_ALFA02-PAIS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVA_ALFA02 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVA_ALFA02-NUM_DIR TO
ZEMPLE_ALFA02-NUM_DIR .
MOVE ZVA_ALFA02-MANDT TO
ZEMPLE_ALFA02-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEMPLE_ALFA02'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEMPLE_ALFA02 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEMPLE_ALFA02'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
